version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./Frontend:/app

  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    depends_on:
      - frontend