# Generated by Django 4.2 on 2024-05-14 00:50

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='books',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
