# Generated by Django 4.2 on 2024-05-14 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_order_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_User',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
