# Generated by Django 4.2 on 2024-06-02 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_role'),
    ]

    operations = [
    ]
