# Generated by Django 4.2 on 2024-06-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_genre_genre_genre_name_order_user_and_more'),
        ('books', '0008_merge_20240602_0512'),
    ]

    operations = [
    ]
