# Generated by Django 4.2 on 2024-06-02 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_user_address_remove_user_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dni',
        ),
    ]
