# Generated by Django 4.2 on 2024-06-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_userslibroteka'),
    ]

    operations = [
        migrations.AddField(
            model_name='userslibroteka',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
            preserve_default=False,
        ),
    ]
