# Generated by Django 4.2 on 2024-06-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_remove_order_user_order_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='books',
            field=models.JSONField(default=list),
        ),
    ]
