# Generated by Django 5.0.2 on 2024-03-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibrotekaApp', '0003_tumodelo_remove_product_name_product_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Título predeterminado', max_length=255, verbose_name='Título')),
                ('description', models.TextField(default='Descripción predeterminada', verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
            ],
        ),
    ]
